Add PR template
Otus-DevOps-2021-11/BeremennaV16_infra pull request #1
Opened 2021-12-25 13:10 UTC by BeremennaV16

Accetped

2021-12-26 11:29 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз, оставил комментарий к файлу
ДЗ возвращаю на доработку

2021-12-26 11:29 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно =)
Нужно поправить

2022-01-03 08:13 UTC, BeremennaV16 commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
поправил

2022-01-04 10:31 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув!)

2022-01-04 16:28 UTC, merged