Terraform 2
Otus-DevOps-2021-11/BeremennaV16_infra pull request #6
Opened 2022-01-23 15:35 UTC by BeremennaV16

# Выполнено ДЗ №

 - [ +] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-01-23 15:38 UTC, BeremennaV16 commented
Добрый день, были проблемы с тестом, поправил основные, но вот с 
cd terraform/stage && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example` exit_status should eq 0
какой-то треш.
Кстати, поженил отус и гит, статус домашек на отусе также не проверены, как мне получить мой заветный ключ от яндекс облака?) В отусе пишут как только сделаете мерч в свой меин в д/з по облаку))

2022-01-24 16:43 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу
Кажется что править не так много
ДЗ возвращаю на доработку =)

2022-01-24 16:43 UTC, mrgreyves commented on terraform/modules/app/variables.tf
> +  default = "ru-central1-a"
Для других переменных стоит добавить значения по дефолту =)

2022-01-24 19:22 UTC, BeremennaV16 commented on terraform/modules/app/variables.tf
> +  default = "ru-central1-a"
Владимир, для сабнета и публичного ключа определить переменные по дефолту невозможно, с ключом в плане безопасности, сеть у нас создается отдельная для виртуалок.
Disk_image определил, результатов 0, посмотрел у коллег, что сдали дз, в модулях две переменные по дефолту, сделал также...

2022-01-24 19:34 UTC, BeremennaV16 commented
Поправил, проблема была с блоком 
terraform {
  required_providers {
    yandex = {
      source  = "yandex-cloud/yandex"
      version = "0.61.0"
    }
  }
}

2022-01-24 20:02 UTC, BeremennaV16 commented
Кстати, поженил отус и гит, статус домашек на отусе также не проверены, как мне получить мой заветный ключ от яндекс облака?) В отусе пишут как только сделаете мерч в свой меин в д/з по облаку))
Помогите еще с этим, пожалуйста

2022-01-24 20:13 UTC, BeremennaV16 commented
Промик получил, спасибо!

2022-01-26 07:48 UTC, mrgreyves approved these changes
Здравствуйте!)
С этим дз все ок
По поводу тех которые не проставлены в лк, пинганите меня в слаке
Там уже с вами решим =)

2022-01-29 13:13 UTC, merged