Ansible 3
Otus-DevOps-2021-11/BeremennaV16_infra pull request #9
Opened 2022-02-09 16:46 UTC by BeremennaV16

# Выполнено ДЗ №

 - [*] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-02-09 16:48 UTC, artyom-markov commented
Выполнено все, кроме звездочек, в тестах проблемы с пакером, тест не проваливается в директорию плейбукс

2022-02-10 08:23 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с методичкой, кажется что не все файлы находятся там где должны
Кажется что это можно сделать быстро, дз возвращаю на доработку =)

2022-02-10 10:38 UTC, BeremennaV16 commented
Поправил конфиг packet инстансов, согласно новому расположению плейбуков

2022-02-11 14:53 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув =)

2022-02-12 11:21 UTC, merged